config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :bookings, only: [:new, :create, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  resources :bookings, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :date_from, presence: true
  validates :date_to, presence: true

end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_one_attached :image


  validates :address, :price, :capacity, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [:address],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :flats

  validates :email, uniqueness: true
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(bookings_params)
    @booking.flat = @flat
    @booking.user = current_user

    if @booking.save
      redirect_to flat_booking_path(@flat, @booking)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find(params[:id])
    @booking.update(bookings_params)
    @booking.flat = @flat
    if @booking.save
      redirect_to flat_booking_path(@flat, @booking)
    else
      render :edit
  end
end

private

  def bookings_params
    params.require(:booking).permit(:address, :capacity, :date_to, :date_from, :flat_id)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @flats = Flat.search_by_address(params[:query])
    else
      @flats = Flat.all
    end
  end




  def show
    @flat = Flat.find(params[:id])
    # raise
    #Added code EA-28/02
    @markers = [ { lng: @flat.latitude, lat: @flat.longitude } ]

    #raise
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flats_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  private

  def flats_params
    params.require(:flat).permit(:address, :price, :capacity, :rating, :facilities, :photo)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1> Edit your booking <%=@booking.id %></h1>
  <div class="container">
    <div class= "row justify-content-around">
      <div class="col-6">
       <%= simple_form_for([@flat, @booking]) do |f| %>
        <p><strong>Change dates:</strong> <%= f.input :date_from %>
        <p><strong>Change dates:</strong> <%= f.input :date_to %>
       <%= f.submit "Edit booking", class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class= "row justify-content-around" style="margin: 25px">
    <div class="col-md-6">
      <% @bookings.each do |booking| %>
        <div class="t-cardWrap">
          <div class="t-card t-cardLeft">
            <h1>Your Reservation Confirmation</h1>
            <div class="t-title">
              <h2><%= booking.flat.name %></h2>
            </div>
              <div class="t-name">
              <span>Email</span>
              <h2><%= current_user.email %></h2>
            </div>
            <div class="t-number">
              <strong>From:</strong> <%= booking.date_from %> <strong>   To:</strong> <%= booking.date_to %>
              <span></span>
            </div>
          </div>
          <div class="t-card t-cardRight">
            <div class="t-barcode"></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "All Iconic Stays", flats_path, class: "btn btn-primary rounded mt-5"%>

app/views/bookings/new.html.erb
    <div class="container">
      <div class= "row justify-content-around">
        <div class="col-md-8">
          <div class="form-card-background">
            <h3 style="margin-top: 35px; font-size: 20px; font-family: 'open sans'"> Make a Reservation for: </h3>
            <h4><%=@flat.name %></h4>
            <%= simple_form_for [@flat, @booking] do |f| %>
                <p><strong>Choose dates:</strong> <%= f.input :date_from %>
                <p><strong>Choose dates:</strong> <%= f.input :date_to %>
              <%= f.submit "Reserve now", class: "btn btn-primary mt-3" %>
            <% end %>
          </div><!-- end form-card-background -->
        </div>
      </div>
    </div>

app/views/bookings/show.html.erb
  <div class="t-cardWrap">
    <div class="t-card t-cardLeft">
      <h1>Your Reservation Confirmation</h1>
      <div class="t-title">
        <h2><%= @flat.name %></h2>
      </div>
        <div class="t-name">
        <span>Email</span>
        <h2><%= current_user.email %></h2>
      </div>
      <div class="t-number">
        <strong>From:</strong> <%= @booking.date_from %> <strong>&nbsp&nbspTo:</strong> <%= @booking.date_to %>
        <span></span>
      </div>
    </div>
    <div class="t-card t-cardRight">
      <div class="t-barcode"></div>
    </div>
    <%= link_to "All Iconic Stays", flats_path, class: "btn btn-primary rounded mt-5"%>
    <%= link_to "Edit Reservation",  edit_flat_booking_path(@flat, @booking) , class: "btn btn-primary rounded mt-5"%>
    <%= link_to "See All Reservations",  bookings_path, class: "btn btn-primary rounded mt-5"%>
  </div>


      <

app/views/flats/edit.html.erb
<h1><%= Edit Reservation details%></h1>
<div class="container">
  <div class= "row justify-content-around">
    <div class="col-6">
      <%= simple_form_for(flat) do |f| %>
        <p><strong>Address:</strong><%= f.input :address %>
        <p><strong>Capacity:</strong> <%= f.input :capacity %>
        <p><strong>Price:</strong><%= f.input :price %>
        <p><strong>Rating:</strong><%= f.input :rating %>
        <p><strong>Facilities:</strong><%= f.input :facilities %>
       <%= f.submit "Edit Reservation", class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div>
    <h1 style="margin-left: 20px; margin-top: 20px; margin-bottom: 25px">All Iconic Stays</h1>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-md-4">
      <div class="card-trip mb-3 p-3" style="border-radius:10px">

        <% if flat.image.attached? %>
          <%= cl_image_tag flat.image.key, height: 300, width: 400, crop: :fill %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2 class="mb-2" style="width: 170px"><%= flat.name%></h2>
            <p><strong>Capacity:</strong><%= flat.capacity %></p>
            <p><strong>Rating</strong> <% flat.rating&.times do%>
              <i class="fas fa-star" style="color:gold;"></i>
            <% end %>
            <div>
              <%= link_to "View Details", flat_path(flat), class: "btn btn-primary rounded mt-3"%>
            </div>
          <% if flat.user.photo.attached? %>
            <%= cl_image_tag flat.user.photo.key, class: "card-trip-user avatar"%>
          <% end %>
          </div>
          <div class="price">
            <strong>Price: £</strong><strong><%= flat.price %></strong><strong>k</strong>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%#= cl_image_tag(Flat.first.image, width: 400, height: 800, crop: :fill) %>

<div class="container">
  <div class= "row justify-content-around">
    <div class="col-6">
      <%= simple_form_for(@flat) do |f| %>
        <p><strong>Address:</strong><%= f.input :address %>
        <p><strong>Capacity:</strong> <%= f.input :capacity %>
        <p><strong>Price:</strong><%= f.input :price %>
        <p><strong>Rating:</strong><%= f.input :rating %>
        <p><strong>Facilities:</strong><%= f.input :facilities %>
        <%= f.input :photo, as: :file %>
       <%= f.submit "Add a new flat", class: "btn btn-primary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="card-trip-show">
  <% if @flat.image.attached? %>
    <%= cl_image_tag @flat.image.key, crop: :fill %>
  <% end %>
  <div class="card-trip-infos-show">
    <h2 class="mb-2" style="width: 170px"><%= @flat.name%></h2>
    <p><strong>Capacity:</strong><%= @flat.capacity %></p>
    <p><strong>Rating</strong><% @flat.rating&.times do %>
      <i class="fas fa-star" style="color:gold;"></i>
      <% end %>
    <div class="confirmation" style="padding-right: 30px">
      <p class="price-font"><strong>Price: £</strong><strong><%= @flat.price %></strong>
    </div>
  </div>
  <div class="mb-5" style="display: flex; justify-content: space-around; align-items: center">
    <%= link_to "ALL ICONIC STAYS", flats_path, class: "btn btn-primary px-4"%>
    <%= link_to "RESERVE", new_flat_booking_path(@flat), class: "btn btn-primary px-4"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>Iconic Stays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless action_name == "home" %>
    <%= render 'shared/navbar' %>
   <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(<%= image_path "pretty2.jpg" %>);">
  <div class="container">
    <h1><strong> Iconic Stays </strong> </h1>
    <p> Stay in your dream locations because you're worth it!</p>
      <%= form_tag flats_path, method: :get do %>
    <div class="search-container">
        <%= text_field_tag :query,
          params[:query]
        %>
      <% end %>
      <div class="search">
        <%= submit_tag "Search" %>
      </div>
    </div>
    <%#= link_to 'All flats', flats_path, class: "btn btn-primary custom-button"   %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="navbar--logo">
    <%= image_tag 'IC-LOGO.png' %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "HOME", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "MESSAGES", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
            <% if user_signed_in? && current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "wladimir.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New monument", new_flat_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>